### ISSUE TITLE
Timeout on PortManager is set too low and causes port bind errors

### ISSUE THREAD

**Issue by danrossi** [red5pro/red5pro-common#94]
I discovered a bug where UDP port check binding fails due to the low 5ms timeout. Setting it to a higher value helps avoid this issue.

https://github.com/red5pro/red5pro-common/blob/feature/RED5DEV-896/src/main/java/com/red5pro/server/util/PortManager.java#L204

**Comment by mondain** [comment]
@danrossi thanks for the report; I'll add a property to the server, when processed will update the value if present. Otherwise it will continue to default to 5ms; anyone using this library can make the static call to change it at-will with `PortManager.setSoTimeout(10)` or whatever value they prefer.

**Comment by mondain** [comment]
Property read/set on PortManager is in the working branch now.
